/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * (title)
 * API for a custom three-player chess variant game server. Authentication is required via a JWT Bearer token for protected endpoints.
 * OpenAPI spec version: 0.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  BadRequestError,
  ConflictError,
  ForbiddenError,
  GameHistory,
  InternalError,
  NotFoundError,
  UnauthorizedError,
} from ".././model";

import { customInstance } from ".././mutator/custom-instance";
import type { ErrorType } from ".././mutator/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Get the move history of a specific game
 */
export const historyGetGameHistory = (
  gameId: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GameHistory>(
    { url: `/api/history/${gameId}`, method: "GET", signal },
    options,
  );
};

export const getHistoryGetGameHistoryQueryKey = (gameId?: number) => {
  return [`/api/history/${gameId}`] as const;
};

export const getHistoryGetGameHistoryQueryOptions = <
  TData = Awaited<ReturnType<typeof historyGetGameHistory>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  gameId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof historyGetGameHistory>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getHistoryGetGameHistoryQueryKey(gameId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof historyGetGameHistory>>
  > = ({ signal }) => historyGetGameHistory(gameId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!gameId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof historyGetGameHistory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type HistoryGetGameHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof historyGetGameHistory>>
>;
export type HistoryGetGameHistoryQueryError = ErrorType<
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | InternalError
>;

export function useHistoryGetGameHistory<
  TData = Awaited<ReturnType<typeof historyGetGameHistory>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  gameId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof historyGetGameHistory>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof historyGetGameHistory>>,
          TError,
          Awaited<ReturnType<typeof historyGetGameHistory>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHistoryGetGameHistory<
  TData = Awaited<ReturnType<typeof historyGetGameHistory>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  gameId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof historyGetGameHistory>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof historyGetGameHistory>>,
          TError,
          Awaited<ReturnType<typeof historyGetGameHistory>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHistoryGetGameHistory<
  TData = Awaited<ReturnType<typeof historyGetGameHistory>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  gameId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof historyGetGameHistory>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get the move history of a specific game
 */

export function useHistoryGetGameHistory<
  TData = Awaited<ReturnType<typeof historyGetGameHistory>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  gameId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof historyGetGameHistory>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getHistoryGetGameHistoryQueryOptions(gameId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
