/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * (title)
 * API for a custom three-player chess variant game server. Authentication is required via a JWT Bearer token for protected endpoints.
 * OpenAPI spec version: 0.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  BadRequestError,
  ConflictError,
  ForbiddenError,
  InternalError,
  LeaderboardEntry,
  LeaderboardGetLeaderboardParams,
  NotFoundError,
  UnauthorizedError,
} from ".././model";

import { customInstance } from ".././mutator/custom-instance";
import type { ErrorType } from ".././mutator/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Get the leaderboard
 */
export const leaderboardGetLeaderboard = (
  params: LeaderboardGetLeaderboardParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<LeaderboardEntry[]>(
    { url: `/api/leaderboard/`, method: "GET", params, signal },
    options,
  );
};

export const getLeaderboardGetLeaderboardQueryKey = (
  params?: LeaderboardGetLeaderboardParams,
) => {
  return [`/api/leaderboard/`, ...(params ? [params] : [])] as const;
};

export const getLeaderboardGetLeaderboardQueryOptions = <
  TData = Awaited<ReturnType<typeof leaderboardGetLeaderboard>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  params: LeaderboardGetLeaderboardParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leaderboardGetLeaderboard>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getLeaderboardGetLeaderboardQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof leaderboardGetLeaderboard>>
  > = ({ signal }) => leaderboardGetLeaderboard(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof leaderboardGetLeaderboard>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type LeaderboardGetLeaderboardQueryResult = NonNullable<
  Awaited<ReturnType<typeof leaderboardGetLeaderboard>>
>;
export type LeaderboardGetLeaderboardQueryError = ErrorType<
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | InternalError
>;

export function useLeaderboardGetLeaderboard<
  TData = Awaited<ReturnType<typeof leaderboardGetLeaderboard>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  params: LeaderboardGetLeaderboardParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leaderboardGetLeaderboard>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof leaderboardGetLeaderboard>>,
          TError,
          Awaited<ReturnType<typeof leaderboardGetLeaderboard>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLeaderboardGetLeaderboard<
  TData = Awaited<ReturnType<typeof leaderboardGetLeaderboard>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  params: LeaderboardGetLeaderboardParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leaderboardGetLeaderboard>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof leaderboardGetLeaderboard>>,
          TError,
          Awaited<ReturnType<typeof leaderboardGetLeaderboard>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLeaderboardGetLeaderboard<
  TData = Awaited<ReturnType<typeof leaderboardGetLeaderboard>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  params: LeaderboardGetLeaderboardParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leaderboardGetLeaderboard>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get the leaderboard
 */

export function useLeaderboardGetLeaderboard<
  TData = Awaited<ReturnType<typeof leaderboardGetLeaderboard>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  params: LeaderboardGetLeaderboardParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof leaderboardGetLeaderboard>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getLeaderboardGetLeaderboardQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
