/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Aide axum Open API
 * # Todo API

A very simple Todo server with documentation.

The purpose is to showcase the documentation workflow of Aide rather
than a correct implementation.

 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AppError,
  ApplyMoves,
  BoardState,
  CommitMove,
  ThinkInput,
  ThinkResult,
} from ".././model";

import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getHexDefaultRadius = (
  radius: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<BoardState>(
    { url: `/hex/default/${radius}`, method: "GET", signal },
    options,
  );
};

export const getGetHexDefaultRadiusQueryKey = (radius?: number) => {
  return [`/hex/default/${radius}`] as const;
};

export const getGetHexDefaultRadiusQueryOptions = <
  TData = Awaited<ReturnType<typeof getHexDefaultRadius>>,
  TError = ErrorType<AppError>,
>(
  radius: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getHexDefaultRadius>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetHexDefaultRadiusQueryKey(radius);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getHexDefaultRadius>>
  > = ({ signal }) => getHexDefaultRadius(radius, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!radius,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getHexDefaultRadius>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetHexDefaultRadiusQueryResult = NonNullable<
  Awaited<ReturnType<typeof getHexDefaultRadius>>
>;
export type GetHexDefaultRadiusQueryError = ErrorType<AppError>;

export function useGetHexDefaultRadius<
  TData = Awaited<ReturnType<typeof getHexDefaultRadius>>,
  TError = ErrorType<AppError>,
>(
  radius: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getHexDefaultRadius>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHexDefaultRadius>>,
          TError,
          Awaited<ReturnType<typeof getHexDefaultRadius>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetHexDefaultRadius<
  TData = Awaited<ReturnType<typeof getHexDefaultRadius>>,
  TError = ErrorType<AppError>,
>(
  radius: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getHexDefaultRadius>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHexDefaultRadius>>,
          TError,
          Awaited<ReturnType<typeof getHexDefaultRadius>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetHexDefaultRadius<
  TData = Awaited<ReturnType<typeof getHexDefaultRadius>>,
  TError = ErrorType<AppError>,
>(
  radius: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getHexDefaultRadius>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetHexDefaultRadius<
  TData = Awaited<ReturnType<typeof getHexDefaultRadius>>,
  TError = ErrorType<AppError>,
>(
  radius: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getHexDefaultRadius>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetHexDefaultRadiusQueryOptions(radius, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const postHexMakeMove = (
  commitMove: CommitMove,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<BoardState>(
    {
      url: `/hex/make_move`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: commitMove,
      signal,
    },
    options,
  );
};

export const getPostHexMakeMoveMutationOptions = <
  TError = ErrorType<AppError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postHexMakeMove>>,
    TError,
    { data: CommitMove },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postHexMakeMove>>,
  TError,
  { data: CommitMove },
  TContext
> => {
  const mutationKey = ["postHexMakeMove"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postHexMakeMove>>,
    { data: CommitMove }
  > = (props) => {
    const { data } = props ?? {};

    return postHexMakeMove(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostHexMakeMoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof postHexMakeMove>>
>;
export type PostHexMakeMoveMutationBody = CommitMove;
export type PostHexMakeMoveMutationError = ErrorType<AppError>;

export const usePostHexMakeMove = <
  TError = ErrorType<AppError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postHexMakeMove>>,
      TError,
      { data: CommitMove },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postHexMakeMove>>,
  TError,
  { data: CommitMove },
  TContext
> => {
  const mutationOptions = getPostHexMakeMoveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const postHexThink = (
  thinkInput: ThinkInput,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ThinkResult>(
    {
      url: `/hex/think`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: thinkInput,
      signal,
    },
    options,
  );
};

export const getPostHexThinkMutationOptions = <
  TError = ErrorType<AppError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postHexThink>>,
    TError,
    { data: ThinkInput },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postHexThink>>,
  TError,
  { data: ThinkInput },
  TContext
> => {
  const mutationKey = ["postHexThink"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postHexThink>>,
    { data: ThinkInput }
  > = (props) => {
    const { data } = props ?? {};

    return postHexThink(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostHexThinkMutationResult = NonNullable<
  Awaited<ReturnType<typeof postHexThink>>
>;
export type PostHexThinkMutationBody = ThinkInput;
export type PostHexThinkMutationError = ErrorType<AppError>;

export const usePostHexThink = <
  TError = ErrorType<AppError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postHexThink>>,
      TError,
      { data: ThinkInput },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postHexThink>>,
  TError,
  { data: ThinkInput },
  TContext
> => {
  const mutationOptions = getPostHexThinkMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const postHexApplyMoves = (
  applyMoves: ApplyMoves,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<BoardState>(
    {
      url: `/hex/apply_moves`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: applyMoves,
      signal,
    },
    options,
  );
};

export const getPostHexApplyMovesMutationOptions = <
  TError = ErrorType<AppError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postHexApplyMoves>>,
    TError,
    { data: ApplyMoves },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postHexApplyMoves>>,
  TError,
  { data: ApplyMoves },
  TContext
> => {
  const mutationKey = ["postHexApplyMoves"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postHexApplyMoves>>,
    { data: ApplyMoves }
  > = (props) => {
    const { data } = props ?? {};

    return postHexApplyMoves(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostHexApplyMovesMutationResult = NonNullable<
  Awaited<ReturnType<typeof postHexApplyMoves>>
>;
export type PostHexApplyMovesMutationBody = ApplyMoves;
export type PostHexApplyMovesMutationError = ErrorType<AppError>;

export const usePostHexApplyMoves = <
  TError = ErrorType<AppError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postHexApplyMoves>>,
      TError,
      { data: ApplyMoves },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postHexApplyMoves>>,
  TError,
  { data: ApplyMoves },
  TContext
> => {
  const mutationOptions = getPostHexApplyMovesMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * This documentation page.
 */
export const getDocs = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<string>(
    { url: `/docs`, method: "GET", signal },
    options,
  );
};

export const getGetDocsQueryKey = () => {
  return [`/docs`] as const;
};

export const getGetDocsQueryOptions = <
  TData = Awaited<ReturnType<typeof getDocs>>,
  TError = ErrorType<AppError>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getDocs>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDocsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocs>>> = ({
    signal,
  }) => getDocs(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDocs>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDocsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDocs>>
>;
export type GetDocsQueryError = ErrorType<AppError>;

export function useGetDocs<
  TData = Awaited<ReturnType<typeof getDocs>>,
  TError = ErrorType<AppError>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDocs>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocs>>,
          TError,
          Awaited<ReturnType<typeof getDocs>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDocs<
  TData = Awaited<ReturnType<typeof getDocs>>,
  TError = ErrorType<AppError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDocs>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocs>>,
          TError,
          Awaited<ReturnType<typeof getDocs>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDocs<
  TData = Awaited<ReturnType<typeof getDocs>>,
  TError = ErrorType<AppError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDocs>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetDocs<
  TData = Awaited<ReturnType<typeof getDocs>>,
  TError = ErrorType<AppError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDocs>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetDocsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * This documentation page.
 */
export const getDocsRedoc = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<string>(
    { url: `/docs/redoc`, method: "GET", signal },
    options,
  );
};

export const getGetDocsRedocQueryKey = () => {
  return [`/docs/redoc`] as const;
};

export const getGetDocsRedocQueryOptions = <
  TData = Awaited<ReturnType<typeof getDocsRedoc>>,
  TError = ErrorType<AppError>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getDocsRedoc>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDocsRedocQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocsRedoc>>> = ({
    signal,
  }) => getDocsRedoc(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDocsRedoc>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDocsRedocQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDocsRedoc>>
>;
export type GetDocsRedocQueryError = ErrorType<AppError>;

export function useGetDocsRedoc<
  TData = Awaited<ReturnType<typeof getDocsRedoc>>,
  TError = ErrorType<AppError>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDocsRedoc>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocsRedoc>>,
          TError,
          Awaited<ReturnType<typeof getDocsRedoc>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDocsRedoc<
  TData = Awaited<ReturnType<typeof getDocsRedoc>>,
  TError = ErrorType<AppError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDocsRedoc>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocsRedoc>>,
          TError,
          Awaited<ReturnType<typeof getDocsRedoc>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDocsRedoc<
  TData = Awaited<ReturnType<typeof getDocsRedoc>>,
  TError = ErrorType<AppError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDocsRedoc>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetDocsRedoc<
  TData = Awaited<ReturnType<typeof getDocsRedoc>>,
  TError = ErrorType<AppError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDocsRedoc>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetDocsRedocQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * This documentation page.
 */
export const getDocsSwagger = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<string>(
    { url: `/docs/swagger`, method: "GET", signal },
    options,
  );
};

export const getGetDocsSwaggerQueryKey = () => {
  return [`/docs/swagger`] as const;
};

export const getGetDocsSwaggerQueryOptions = <
  TData = Awaited<ReturnType<typeof getDocsSwagger>>,
  TError = ErrorType<AppError>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getDocsSwagger>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDocsSwaggerQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocsSwagger>>> = ({
    signal,
  }) => getDocsSwagger(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDocsSwagger>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDocsSwaggerQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDocsSwagger>>
>;
export type GetDocsSwaggerQueryError = ErrorType<AppError>;

export function useGetDocsSwagger<
  TData = Awaited<ReturnType<typeof getDocsSwagger>>,
  TError = ErrorType<AppError>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDocsSwagger>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocsSwagger>>,
          TError,
          Awaited<ReturnType<typeof getDocsSwagger>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDocsSwagger<
  TData = Awaited<ReturnType<typeof getDocsSwagger>>,
  TError = ErrorType<AppError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDocsSwagger>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocsSwagger>>,
          TError,
          Awaited<ReturnType<typeof getDocsSwagger>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDocsSwagger<
  TData = Awaited<ReturnType<typeof getDocsSwagger>>,
  TError = ErrorType<AppError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDocsSwagger>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetDocsSwagger<
  TData = Awaited<ReturnType<typeof getDocsSwagger>>,
  TError = ErrorType<AppError>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDocsSwagger>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetDocsSwaggerQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
