/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Aide axum Open API
 * # Todo API

A very simple Todo server with documentation.

The purpose is to showcase the documentation workflow of Aide rather
than a correct implementation.

 */

/**
 * The player who is to move from this position.
 * @minimum 0
 */
export type ApiNodeAttributesPlayerToMove = number | null;
