/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Aide axum Open API
 * # Todo API

A very simple Todo server with documentation.

The purpose is to showcase the documentation workflow of Aide rather
than a correct implementation.

 */

/**
 * A default error response for most API errors.
 */
export interface AppError {
  /** An error message. */
  error: string;
  /** Optional Additional error details. */
  error_details?: unknown;
  /** A unique error ID. */
  error_id: string;
}
