/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Aide axum Open API
 * # Todo API

A very simple Todo server with documentation.

The purpose is to showcase the documentation workflow of Aide rather
than a correct implementation.

 */
import type { BoardState } from "./boardState";

export interface ThinkInput {
  board_state: BoardState;
  key: string;
  /** @minimum 0 */
  number_of_rollouts: number;
}
