/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Aide axum Open API
 * # Todo API

A very simple Todo server with documentation.

The purpose is to showcase the documentation workflow of Aide rather
than a correct implementation.

 */

/**
 * A single Todo item.
 */
export interface TodoItem {
  /** The description of the item. */
  description: string;
  /** Whether the item was completed. */
  complete: boolean;
  id: string;
}
