/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Aide axum Open API
 * # Todo API

A very simple Todo server with documentation.

The purpose is to showcase the documentation workflow of Aide rather
than a correct implementation.

 */
import type { ApiNodeAttributesNetValue } from "./apiNodeAttributesNetValue";
import type { ApiNodeAttributesPlayerToMove } from "./apiNodeAttributesPlayerToMove";

export interface ApiNodeAttributes {
  is_terminal: boolean;
  move_indexes: number[];
  net_value?: ApiNodeAttributesNetValue;
  /** @minimum 0 */
  player_to_move?: ApiNodeAttributesPlayerToMove;
  /** The raw policy value from the neural network for the move leading to this node. */
  raw_policy: number;
  sum_values: number[];
  /**
   * The number of times this node was visited during the MCTS search.
   * @minimum 0
   */
  visit_count: number;
}
