/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Aide axum Open API
 * # Todo API

A very simple Todo server with documentation.

The purpose is to showcase the documentation workflow of Aide rather
than a correct implementation.

 */

export interface FullCoordinates {
  /**
   * @minimum 0
   * @maximum 255
   */
  i: number;
  /**
   * @minimum -128
   * @maximum 127
   */
  q: number;
  /**
   * @minimum -128
   * @maximum 127
   */
  r: number;
  /**
   * @minimum -128
   * @maximum 127
   */
  s: number;
}
