/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Aide axum Open API
 * # Todo API

A very simple Todo server with documentation.

The purpose is to showcase the documentation workflow of Aide rather
than a correct implementation.

 */

export interface PolicyMovesIn {
  fen: string;
  /** @minimum 0 */
  number_of_moves: number;
}
