/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Aide axum Open API
 * # Todo API

A very simple Todo server with documentation.

The purpose is to showcase the documentation workflow of Aide rather
than a correct implementation.

 */
import type { ChessMoveWrapperDto } from "./chessMoveWrapperDto";
import type { ChessBoardDto } from "./chessBoardDto";
import type { ApiNode } from "./apiNode";

export interface ThinkResultForChessMoveWrapperDtoAndChessBoardDto {
  /** @minimum 0 */
  duration_ms: number;
  moves: ChessMoveWrapperDto[];
  root_board: ChessBoardDto;
  root_position_eval: number[];
  tree: ApiNode;
}
