/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Aide axum Open API
 * # Todo API

A very simple Todo server with documentation.

The purpose is to showcase the documentation workflow of Aide rather
than a correct implementation.

 */
import type { BoardTile } from "./boardTile";
import type { HexPlayer } from "./hexPlayer";
import type { BoardStateWinner } from "./boardStateWinner";

export interface BoardState {
  board: BoardTile[];
  current_turn: HexPlayer;
  eliminated_players: HexPlayer[];
  /** @minimum 0 */
  radius: number;
  winner?: BoardStateWinner;
}
