/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Aide axum Open API
 * # Todo API

A very simple Todo server with documentation.

The purpose is to showcase the documentation workflow of Aide rather
than a correct implementation.

 */

export type HexPlayer = (typeof HexPlayer)[keyof typeof HexPlayer];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HexPlayer = {
  P1: "P1",
  P2: "P2",
  P3: "P3",
} as const;
