/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Aide axum Open API
 * # Todo API

A very simple Todo server with documentation.

The purpose is to showcase the documentation workflow of Aide rather
than a correct implementation.

 */
import type { ThinkResultItem } from "./thinkResultItem";
import type { BoardState } from "./boardState";
import type { ApiNode } from "./apiNode";

export interface ThinkResult {
  /** @minimum 0 */
  duration_ms: number;
  moves: ThinkResultItem[];
  root_board: BoardState;
  root_position_eval: number[];
  tree: ApiNode;
}
