//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18
use sea_orm::entity::prelude::*;

// implement into bot reader model
impl From<ModelEx> for api_autogen::models::ReadBot {
    fn from(b: ModelEx) -> Self {
        api_autogen::models::ReadBot {
            user_id: b.user_id,
            bot_id: b.id,
            username: b.user.into_option().map(|u| u.username).unwrap_or_default(),
            model_key: b.model_key,
            playouts_per_move: b.playouts,
            exploration_factor: b.exploration_factor,
            virtual_loss: b.virtual_loss_weight,
            contempt: b.contempt,
        }
    }
}

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "bots")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,

    #[sea_orm(unique)]
    pub user_id: i64,

    #[sea_orm(column_type = "Text")]
    pub model_key: Option<String>,

    pub playouts: u32,

    #[sea_orm(column_type = "Float")]
    pub exploration_factor: f32,

    #[sea_orm(column_type = "Float")]
    pub virtual_loss_weight: f32,

    #[sea_orm(column_type = "Float")]
    pub contempt: f32,

    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub user: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
