//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;

#[derive(EnumIter, DeriveActiveEnum, Clone, Debug, PartialEq, Eq)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::None)", rename_all = "camelCase")]
pub enum GameStatusDb {
    Waiting,
    InProgress,
    CompletedWin,
    CompletedSemiDraw,
    CompletedFullDraw,
}

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "games")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,

    #[sea_orm(column_type = "Text")]
    pub name: String,

    #[sea_orm(column_type = "Text")]
    pub fen: String,

    pub owner_id: Option<i64>,

    #[sea_orm(belongs_to, from = "owner_id", to = "id", relation_enum = "Owner")]
    pub owner: HasOne<super::users::Entity>,

    pub game_status: GameStatusDb,

    pub names_masked: Option<bool>,

    pub material_masked: Option<bool>,

    pub training_mode: Option<bool>,

    #[sea_orm(has_many)]
    pub players: HasMany<super::players::Entity>,

    #[sea_orm(has_many)]
    pub history: HasMany<super::history::Entity>,

    pub suggested_time_for_move_secs: Option<i32>,

    pub tournament_id: Option<i64>,

    #[sea_orm(belongs_to, from = "tournament_id", to = "id", relation_enum = "Tournament")]
    pub tournament: HasOne<super::tournament::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
