//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use crate::entity::db_color::ColorDb;

#[derive(EnumIter, DeriveActiveEnum, Clone, Debug, PartialEq, Eq)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::None)", rename_all = "camelCase")]
pub enum GameStatusDb {
    Waiting,
    InProgress,
    CompletedWin,
    CompletedSemiDraw,
    CompletedFullDraw,
}

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "history")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,

    #[sea_orm(column_type = "Text")]
    pub fen: String,

    #[sea_orm(column_type = "Text")]
    pub move_uci: String,

    pub turn: i64,

    pub color: ColorDb,

    pub game_id: i64,

    #[sea_orm(
        belongs_to,
        from = "game_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub games: HasOne<super::games::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
