//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use api_autogen::models;
use crate::entity::db_color::ColorDb;

#[derive(EnumIter, DeriveActiveEnum, Clone, Debug, PartialEq, Eq)]
#[sea_orm(
    rs_type = "String",
    db_type = "String(StringLen::None)",
    rename_all = "camelCase"
)]
pub enum GameRelationDb {
    None,
    Winner,
    Draw,
    Loser,
}

impl From<models::GameRelation> for GameRelationDb {
    fn from(r: models::GameRelation) -> Self {
        match r {
            models::GameRelation::Winner => GameRelationDb::Winner,
            models::GameRelation::Loser => GameRelationDb::Loser,
            models::GameRelation::Draw => GameRelationDb::Draw,
        }
    }
}

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "players")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub game_id: i64,

    #[sea_orm(primary_key)]
    pub user_id: i64,

    pub color: ColorDb,

    pub relation: GameRelationDb,

    #[sea_orm(
        belongs_to,
        from = "game_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub games: HasOne<super::games::Entity>,
    
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
