//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use crate::entity::db_color::ColorDb;


#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "tournament")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,

    #[sea_orm(column_type = "Text")]
    pub name: String,

    #[sea_orm(has_many)]
    pub games: HasMany<super::games::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
