//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use crate::entity::users;
use api_autogen::models::{MeUser, User, UserType};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(EnumIter, DeriveActiveEnum, Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "String(StringLen::None)",
    rename_all = "camelCase"
)]
pub enum UserTypeDb {
    Normal,
    Admin,
    Bot,
}

impl From<UserTypeDb> for UserType {
    fn from(t: UserTypeDb) -> Self {
        match t {
            UserTypeDb::Normal => UserType::Regular,
            UserTypeDb::Admin => UserType::Admin,
            UserTypeDb::Bot => UserType::Bot,
        }
    }
}

impl From<Model> for User {
    fn from(u: users::Model) -> Self {
        User {
            id: u.id,
            username: u.username,
            r#type: UserType::from(u.user_type),
        }
    }
}

impl From<Model>  for MeUser {
    fn from(u: users::Model) -> Self {
        MeUser {
            id: u.id,
            username: u.username,
            lichess_rating: u.lichess_rating,
            chess_com_rating: u.chess_com_rating,
            fide_rating: u.fide_rating,
            experience_with_chess: u.experience_with_chess,
            r#type: UserType::from(u.user_type),
        }
    }
}

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,

    #[sea_orm(column_type = "Text", unique)]
    pub username: String,

    #[sea_orm(column_type = "Text")]
    pub password_hash: String,

    pub lichess_rating: Option<u16>,

    pub chess_com_rating: Option<u16>,

    pub fide_rating: Option<u16>,

    pub experience_with_chess: Option<u8>,

    #[sea_orm(column_type = "Text")]
    pub user_type: UserTypeDb,

    #[sea_orm(has_many)]
    pub owner_games: HasMany<super::games::Entity>,

    #[sea_orm(has_many)]
    pub players: HasMany<super::players::Entity>,

    #[sea_orm(has_one)]
    pub bot: HasOne<super::bot::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
