/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Aide axum Open API
 * # Todo API

A very simple Todo server with documentation.

The purpose is to showcase the documentation workflow of Aide rather
than a correct implementation.

 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AppError,
  ApplyMoves,
  ApplyMovesOutput,
  AttackMapsIn,
  AttackMapsOut,
  PolicyMovesIn,
  PolicyMovesOut,
  ThinkInput,
  ThinkResultForChessMoveWrapperDtoAndChessBoardDto,
} from ".././model";

import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const postChessThink = (
  thinkInput: ThinkInput,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ThinkResultForChessMoveWrapperDtoAndChessBoardDto>(
    { url: `/chess/think`, method: "POST", headers: { "Content-Type": "application/json" }, data: thinkInput, signal },
    options,
  );
};

export const getPostChessThinkMutationOptions = <TError = ErrorType<AppError>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof postChessThink>>, TError, { data: ThinkInput }, TContext>;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<Awaited<ReturnType<typeof postChessThink>>, TError, { data: ThinkInput }, TContext> => {
  const mutationKey = ["postChessThink"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postChessThink>>, { data: ThinkInput }> = (props) => {
    const { data } = props ?? {};

    return postChessThink(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostChessThinkMutationResult = NonNullable<Awaited<ReturnType<typeof postChessThink>>>;
export type PostChessThinkMutationBody = ThinkInput;
export type PostChessThinkMutationError = ErrorType<AppError>;

export const usePostChessThink = <TError = ErrorType<AppError>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof postChessThink>>, TError, { data: ThinkInput }, TContext>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof postChessThink>>, TError, { data: ThinkInput }, TContext> => {
  const mutationOptions = getPostChessThinkMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const postChessApplyMoves = (
  applyMoves: ApplyMoves,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ApplyMovesOutput>(
    {
      url: `/chess/apply_moves`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: applyMoves,
      signal,
    },
    options,
  );
};

export const getPostChessApplyMovesMutationOptions = <TError = ErrorType<AppError>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postChessApplyMoves>>,
    TError,
    { data: ApplyMoves },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<Awaited<ReturnType<typeof postChessApplyMoves>>, TError, { data: ApplyMoves }, TContext> => {
  const mutationKey = ["postChessApplyMoves"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postChessApplyMoves>>, { data: ApplyMoves }> = (
    props,
  ) => {
    const { data } = props ?? {};

    return postChessApplyMoves(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostChessApplyMovesMutationResult = NonNullable<Awaited<ReturnType<typeof postChessApplyMoves>>>;
export type PostChessApplyMovesMutationBody = ApplyMoves;
export type PostChessApplyMovesMutationError = ErrorType<AppError>;

export const usePostChessApplyMoves = <TError = ErrorType<AppError>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postChessApplyMoves>>,
      TError,
      { data: ApplyMoves },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof postChessApplyMoves>>, TError, { data: ApplyMoves }, TContext> => {
  const mutationOptions = getPostChessApplyMovesMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const postChessAttackMaps = (
  attackMapsIn: AttackMapsIn,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<AttackMapsOut>(
    {
      url: `/chess/attack_maps`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: attackMapsIn,
      signal,
    },
    options,
  );
};

export const getPostChessAttackMapsMutationOptions = <TError = ErrorType<AppError>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postChessAttackMaps>>,
    TError,
    { data: AttackMapsIn },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<Awaited<ReturnType<typeof postChessAttackMaps>>, TError, { data: AttackMapsIn }, TContext> => {
  const mutationKey = ["postChessAttackMaps"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postChessAttackMaps>>, { data: AttackMapsIn }> = (
    props,
  ) => {
    const { data } = props ?? {};

    return postChessAttackMaps(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostChessAttackMapsMutationResult = NonNullable<Awaited<ReturnType<typeof postChessAttackMaps>>>;
export type PostChessAttackMapsMutationBody = AttackMapsIn;
export type PostChessAttackMapsMutationError = ErrorType<AppError>;

export const usePostChessAttackMaps = <TError = ErrorType<AppError>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postChessAttackMaps>>,
      TError,
      { data: AttackMapsIn },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof postChessAttackMaps>>, TError, { data: AttackMapsIn }, TContext> => {
  const mutationOptions = getPostChessAttackMapsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const postChessPolicyMoves = (
  policyMovesIn: PolicyMovesIn,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PolicyMovesOut>(
    {
      url: `/chess/policy_moves`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: policyMovesIn,
      signal,
    },
    options,
  );
};

export const getPostChessPolicyMovesMutationOptions = <TError = ErrorType<AppError>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postChessPolicyMoves>>,
    TError,
    { data: PolicyMovesIn },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<Awaited<ReturnType<typeof postChessPolicyMoves>>, TError, { data: PolicyMovesIn }, TContext> => {
  const mutationKey = ["postChessPolicyMoves"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postChessPolicyMoves>>, { data: PolicyMovesIn }> = (
    props,
  ) => {
    const { data } = props ?? {};

    return postChessPolicyMoves(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostChessPolicyMovesMutationResult = NonNullable<Awaited<ReturnType<typeof postChessPolicyMoves>>>;
export type PostChessPolicyMovesMutationBody = PolicyMovesIn;
export type PostChessPolicyMovesMutationError = ErrorType<AppError>;

export const usePostChessPolicyMoves = <TError = ErrorType<AppError>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postChessPolicyMoves>>,
      TError,
      { data: PolicyMovesIn },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof postChessPolicyMoves>>, TError, { data: PolicyMovesIn }, TContext> => {
  const mutationOptions = getPostChessPolicyMovesMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * This documentation page.
 */
export const getDocs = (options?: SecondParameter<typeof customInstance>, signal?: AbortSignal) => {
  return customInstance<string>({ url: `/docs`, method: "GET", signal }, options);
};

export const getGetDocsQueryKey = () => {
  return [`/docs`] as const;
};

export const getGetDocsQueryOptions = <
  TData = Awaited<ReturnType<typeof getDocs>>,
  TError = ErrorType<AppError>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocs>>, TError, TData>>;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDocsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocs>>> = ({ signal }) => getDocs(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDocs>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDocsQueryResult = NonNullable<Awaited<ReturnType<typeof getDocs>>>;
export type GetDocsQueryError = ErrorType<AppError>;

export function useGetDocs<TData = Awaited<ReturnType<typeof getDocs>>, TError = ErrorType<AppError>>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocs>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<Awaited<ReturnType<typeof getDocs>>, TError, Awaited<ReturnType<typeof getDocs>>>,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDocs<TData = Awaited<ReturnType<typeof getDocs>>, TError = ErrorType<AppError>>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocs>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<Awaited<ReturnType<typeof getDocs>>, TError, Awaited<ReturnType<typeof getDocs>>>,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDocs<TData = Awaited<ReturnType<typeof getDocs>>, TError = ErrorType<AppError>>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocs>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetDocs<TData = Awaited<ReturnType<typeof getDocs>>, TError = ErrorType<AppError>>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocs>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetDocsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * This documentation page.
 */
export const getDocsRedoc = (options?: SecondParameter<typeof customInstance>, signal?: AbortSignal) => {
  return customInstance<string>({ url: `/docs/redoc`, method: "GET", signal }, options);
};

export const getGetDocsRedocQueryKey = () => {
  return [`/docs/redoc`] as const;
};

export const getGetDocsRedocQueryOptions = <
  TData = Awaited<ReturnType<typeof getDocsRedoc>>,
  TError = ErrorType<AppError>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocsRedoc>>, TError, TData>>;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDocsRedocQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocsRedoc>>> = ({ signal }) =>
    getDocsRedoc(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDocsRedoc>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDocsRedocQueryResult = NonNullable<Awaited<ReturnType<typeof getDocsRedoc>>>;
export type GetDocsRedocQueryError = ErrorType<AppError>;

export function useGetDocsRedoc<TData = Awaited<ReturnType<typeof getDocsRedoc>>, TError = ErrorType<AppError>>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocsRedoc>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocsRedoc>>,
          TError,
          Awaited<ReturnType<typeof getDocsRedoc>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDocsRedoc<TData = Awaited<ReturnType<typeof getDocsRedoc>>, TError = ErrorType<AppError>>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocsRedoc>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocsRedoc>>,
          TError,
          Awaited<ReturnType<typeof getDocsRedoc>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDocsRedoc<TData = Awaited<ReturnType<typeof getDocsRedoc>>, TError = ErrorType<AppError>>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocsRedoc>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetDocsRedoc<TData = Awaited<ReturnType<typeof getDocsRedoc>>, TError = ErrorType<AppError>>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocsRedoc>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetDocsRedocQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * This documentation page.
 */
export const getDocsSwagger = (options?: SecondParameter<typeof customInstance>, signal?: AbortSignal) => {
  return customInstance<string>({ url: `/docs/swagger`, method: "GET", signal }, options);
};

export const getGetDocsSwaggerQueryKey = () => {
  return [`/docs/swagger`] as const;
};

export const getGetDocsSwaggerQueryOptions = <
  TData = Awaited<ReturnType<typeof getDocsSwagger>>,
  TError = ErrorType<AppError>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocsSwagger>>, TError, TData>>;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDocsSwaggerQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocsSwagger>>> = ({ signal }) =>
    getDocsSwagger(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDocsSwagger>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDocsSwaggerQueryResult = NonNullable<Awaited<ReturnType<typeof getDocsSwagger>>>;
export type GetDocsSwaggerQueryError = ErrorType<AppError>;

export function useGetDocsSwagger<TData = Awaited<ReturnType<typeof getDocsSwagger>>, TError = ErrorType<AppError>>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocsSwagger>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocsSwagger>>,
          TError,
          Awaited<ReturnType<typeof getDocsSwagger>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDocsSwagger<TData = Awaited<ReturnType<typeof getDocsSwagger>>, TError = ErrorType<AppError>>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocsSwagger>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocsSwagger>>,
          TError,
          Awaited<ReturnType<typeof getDocsSwagger>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDocsSwagger<TData = Awaited<ReturnType<typeof getDocsSwagger>>, TError = ErrorType<AppError>>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocsSwagger>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetDocsSwagger<TData = Awaited<ReturnType<typeof getDocsSwagger>>, TError = ErrorType<AppError>>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocsSwagger>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetDocsSwaggerQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
