/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * (title)
 * API for a custom three-player chess variant game server. Authentication is required via a JWT Bearer token for protected endpoints.
 * OpenAPI spec version: 0.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  BadRequestError,
  ConflictError,
  CreateGame,
  FinishGameIn,
  ForbiddenError,
  GameState,
  GamesListGamesParams,
  InternalError,
  JoinGamePayload,
  MakeMovePayload,
  NotFoundError,
  UnauthorizedError,
  WsEvent,
} from ".././model";

import { customInstance } from ".././mutator/custom-instance";
import type { ErrorType } from ".././mutator/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Creates a new game and adds the creator as the first player.
 * @summary Creates a new game lobby
 */
export const gamesCreateGame = (
  createGame: CreateGame,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GameState>(
    {
      url: `/api/games/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createGame,
      signal,
    },
    options,
  );
};

export const getGamesCreateGameMutationOptions = <
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof gamesCreateGame>>,
    TError,
    { data: CreateGame },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof gamesCreateGame>>,
  TError,
  { data: CreateGame },
  TContext
> => {
  const mutationKey = ["gamesCreateGame"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof gamesCreateGame>>,
    { data: CreateGame }
  > = (props) => {
    const { data } = props ?? {};

    return gamesCreateGame(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GamesCreateGameMutationResult = NonNullable<
  Awaited<ReturnType<typeof gamesCreateGame>>
>;
export type GamesCreateGameMutationBody = CreateGame;
export type GamesCreateGameMutationError = ErrorType<
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | InternalError
>;

/**
 * @summary Creates a new game lobby
 */
export const useGamesCreateGame = <
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof gamesCreateGame>>,
      TError,
      { data: CreateGame },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof gamesCreateGame>>,
  TError,
  { data: CreateGame },
  TContext
> => {
  const mutationOptions = getGamesCreateGameMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Returns a list of games that are in the 'waiting' state and not full.
 * @summary Lists available games to join
 */
export const gamesListGames = (
  params?: GamesListGamesParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GameState[]>(
    { url: `/api/games/`, method: "GET", params, signal },
    options,
  );
};

export const getGamesListGamesQueryKey = (params?: GamesListGamesParams) => {
  return [`/api/games/`, ...(params ? [params] : [])] as const;
};

export const getGamesListGamesQueryOptions = <
  TData = Awaited<ReturnType<typeof gamesListGames>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  params?: GamesListGamesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof gamesListGames>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGamesListGamesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof gamesListGames>>> = ({
    signal,
  }) => gamesListGames(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof gamesListGames>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GamesListGamesQueryResult = NonNullable<
  Awaited<ReturnType<typeof gamesListGames>>
>;
export type GamesListGamesQueryError = ErrorType<
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | InternalError
>;

export function useGamesListGames<
  TData = Awaited<ReturnType<typeof gamesListGames>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  params: undefined | GamesListGamesParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof gamesListGames>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesListGames>>,
          TError,
          Awaited<ReturnType<typeof gamesListGames>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGamesListGames<
  TData = Awaited<ReturnType<typeof gamesListGames>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  params?: GamesListGamesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof gamesListGames>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesListGames>>,
          TError,
          Awaited<ReturnType<typeof gamesListGames>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGamesListGames<
  TData = Awaited<ReturnType<typeof gamesListGames>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  params?: GamesListGamesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof gamesListGames>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Lists available games to join
 */

export function useGamesListGames<
  TData = Awaited<ReturnType<typeof gamesListGames>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  params?: GamesListGamesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof gamesListGames>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGamesListGamesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Finish a game in a specific outcome (Admin only)
 */
export const gamesFinishGameIn = (
  gameId: number,
  finishGameIn: FinishGameIn,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    {
      url: `/api/games/${gameId}/admin/finish`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: finishGameIn,
      signal,
    },
    options,
  );
};

export const getGamesFinishGameInMutationOptions = <
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof gamesFinishGameIn>>,
    TError,
    { gameId: number; data: FinishGameIn },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof gamesFinishGameIn>>,
  TError,
  { gameId: number; data: FinishGameIn },
  TContext
> => {
  const mutationKey = ["gamesFinishGameIn"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof gamesFinishGameIn>>,
    { gameId: number; data: FinishGameIn }
  > = (props) => {
    const { gameId, data } = props ?? {};

    return gamesFinishGameIn(gameId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GamesFinishGameInMutationResult = NonNullable<
  Awaited<ReturnType<typeof gamesFinishGameIn>>
>;
export type GamesFinishGameInMutationBody = FinishGameIn;
export type GamesFinishGameInMutationError = ErrorType<
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | InternalError
>;

/**
 * @summary Finish a game in a specific outcome (Admin only)
 */
export const useGamesFinishGameIn = <
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof gamesFinishGameIn>>,
      TError,
      { gameId: number; data: FinishGameIn },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof gamesFinishGameIn>>,
  TError,
  { gameId: number; data: FinishGameIn },
  TContext
> => {
  const mutationOptions = getGamesFinishGameInMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Used only for type generation.
Actual subscription to game events is done via WebSocket at /ws
 */
export const gamesSubscribeToGameEvents = (
  gameId: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<WsEvent>(
    { url: `/api/games/${gameId}/events`, method: "GET", signal },
    options,
  );
};

export const getGamesSubscribeToGameEventsQueryKey = (gameId?: number) => {
  return [`/api/games/${gameId}/events`] as const;
};

export const getGamesSubscribeToGameEventsQueryOptions = <
  TData = Awaited<ReturnType<typeof gamesSubscribeToGameEvents>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  gameId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof gamesSubscribeToGameEvents>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGamesSubscribeToGameEventsQueryKey(gameId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof gamesSubscribeToGameEvents>>
  > = ({ signal }) =>
    gamesSubscribeToGameEvents(gameId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!gameId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof gamesSubscribeToGameEvents>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GamesSubscribeToGameEventsQueryResult = NonNullable<
  Awaited<ReturnType<typeof gamesSubscribeToGameEvents>>
>;
export type GamesSubscribeToGameEventsQueryError = ErrorType<
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | InternalError
>;

export function useGamesSubscribeToGameEvents<
  TData = Awaited<ReturnType<typeof gamesSubscribeToGameEvents>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  gameId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof gamesSubscribeToGameEvents>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesSubscribeToGameEvents>>,
          TError,
          Awaited<ReturnType<typeof gamesSubscribeToGameEvents>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGamesSubscribeToGameEvents<
  TData = Awaited<ReturnType<typeof gamesSubscribeToGameEvents>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  gameId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof gamesSubscribeToGameEvents>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesSubscribeToGameEvents>>,
          TError,
          Awaited<ReturnType<typeof gamesSubscribeToGameEvents>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGamesSubscribeToGameEvents<
  TData = Awaited<ReturnType<typeof gamesSubscribeToGameEvents>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  gameId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof gamesSubscribeToGameEvents>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGamesSubscribeToGameEvents<
  TData = Awaited<ReturnType<typeof gamesSubscribeToGameEvents>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  gameId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof gamesSubscribeToGameEvents>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGamesSubscribeToGameEventsQueryOptions(
    gameId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Join an existing game
 */
export const gamesJoinGame = (
  gameId: number,
  joinGamePayload: JoinGamePayload,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    {
      url: `/api/games/${gameId}/join`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: joinGamePayload,
      signal,
    },
    options,
  );
};

export const getGamesJoinGameMutationOptions = <
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof gamesJoinGame>>,
    TError,
    { gameId: number; data: JoinGamePayload },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof gamesJoinGame>>,
  TError,
  { gameId: number; data: JoinGamePayload },
  TContext
> => {
  const mutationKey = ["gamesJoinGame"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof gamesJoinGame>>,
    { gameId: number; data: JoinGamePayload }
  > = (props) => {
    const { gameId, data } = props ?? {};

    return gamesJoinGame(gameId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GamesJoinGameMutationResult = NonNullable<
  Awaited<ReturnType<typeof gamesJoinGame>>
>;
export type GamesJoinGameMutationBody = JoinGamePayload;
export type GamesJoinGameMutationError = ErrorType<
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | InternalError
>;

/**
 * @summary Join an existing game
 */
export const useGamesJoinGame = <
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof gamesJoinGame>>,
      TError,
      { gameId: number; data: JoinGamePayload },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof gamesJoinGame>>,
  TError,
  { gameId: number; data: JoinGamePayload },
  TContext
> => {
  const mutationOptions = getGamesJoinGameMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Leave a game
 */
export const gamesLeaveGame = (
  gameId: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/api/games/${gameId}/leave`, method: "POST", signal },
    options,
  );
};

export const getGamesLeaveGameMutationOptions = <
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof gamesLeaveGame>>,
    TError,
    { gameId: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof gamesLeaveGame>>,
  TError,
  { gameId: number },
  TContext
> => {
  const mutationKey = ["gamesLeaveGame"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof gamesLeaveGame>>,
    { gameId: number }
  > = (props) => {
    const { gameId } = props ?? {};

    return gamesLeaveGame(gameId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GamesLeaveGameMutationResult = NonNullable<
  Awaited<ReturnType<typeof gamesLeaveGame>>
>;

export type GamesLeaveGameMutationError = ErrorType<
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | InternalError
>;

/**
 * @summary Leave a game
 */
export const useGamesLeaveGame = <
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof gamesLeaveGame>>,
      TError,
      { gameId: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof gamesLeaveGame>>,
  TError,
  { gameId: number },
  TContext
> => {
  const mutationOptions = getGamesLeaveGameMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Make a move in a game
 */
export const gamesMakeMove = (
  gameId: number,
  makeMovePayload: MakeMovePayload,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    {
      url: `/api/games/${gameId}/move`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: makeMovePayload,
      signal,
    },
    options,
  );
};

export const getGamesMakeMoveMutationOptions = <
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof gamesMakeMove>>,
    TError,
    { gameId: number; data: MakeMovePayload },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof gamesMakeMove>>,
  TError,
  { gameId: number; data: MakeMovePayload },
  TContext
> => {
  const mutationKey = ["gamesMakeMove"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof gamesMakeMove>>,
    { gameId: number; data: MakeMovePayload }
  > = (props) => {
    const { gameId, data } = props ?? {};

    return gamesMakeMove(gameId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GamesMakeMoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof gamesMakeMove>>
>;
export type GamesMakeMoveMutationBody = MakeMovePayload;
export type GamesMakeMoveMutationError = ErrorType<
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | InternalError
>;

/**
 * @summary Make a move in a game
 */
export const useGamesMakeMove = <
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof gamesMakeMove>>,
      TError,
      { gameId: number; data: MakeMovePayload },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof gamesMakeMove>>,
  TError,
  { gameId: number; data: MakeMovePayload },
  TContext
> => {
  const mutationOptions = getGamesMakeMoveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Start a game, if all player slots are filled and you are the creator
 */
export const gamesStartGame = (
  gameId: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/api/games/${gameId}/start`, method: "POST", signal },
    options,
  );
};

export const getGamesStartGameMutationOptions = <
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof gamesStartGame>>,
    TError,
    { gameId: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof gamesStartGame>>,
  TError,
  { gameId: number },
  TContext
> => {
  const mutationKey = ["gamesStartGame"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof gamesStartGame>>,
    { gameId: number }
  > = (props) => {
    const { gameId } = props ?? {};

    return gamesStartGame(gameId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GamesStartGameMutationResult = NonNullable<
  Awaited<ReturnType<typeof gamesStartGame>>
>;

export type GamesStartGameMutationError = ErrorType<
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | InternalError
>;

/**
 * @summary Start a game, if all player slots are filled and you are the creator
 */
export const useGamesStartGame = <
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof gamesStartGame>>,
      TError,
      { gameId: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof gamesStartGame>>,
  TError,
  { gameId: number },
  TContext
> => {
  const mutationOptions = getGamesStartGameMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get the full state of a specific game
 */
export const gamesGetGameState = (
  gameId: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GameState>(
    { url: `/api/games/${gameId}/state`, method: "GET", signal },
    options,
  );
};

export const getGamesGetGameStateQueryKey = (gameId?: number) => {
  return [`/api/games/${gameId}/state`] as const;
};

export const getGamesGetGameStateQueryOptions = <
  TData = Awaited<ReturnType<typeof gamesGetGameState>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  gameId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof gamesGetGameState>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGamesGetGameStateQueryKey(gameId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof gamesGetGameState>>
  > = ({ signal }) => gamesGetGameState(gameId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!gameId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof gamesGetGameState>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GamesGetGameStateQueryResult = NonNullable<
  Awaited<ReturnType<typeof gamesGetGameState>>
>;
export type GamesGetGameStateQueryError = ErrorType<
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | InternalError
>;

export function useGamesGetGameState<
  TData = Awaited<ReturnType<typeof gamesGetGameState>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  gameId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof gamesGetGameState>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesGetGameState>>,
          TError,
          Awaited<ReturnType<typeof gamesGetGameState>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGamesGetGameState<
  TData = Awaited<ReturnType<typeof gamesGetGameState>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  gameId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof gamesGetGameState>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesGetGameState>>,
          TError,
          Awaited<ReturnType<typeof gamesGetGameState>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGamesGetGameState<
  TData = Awaited<ReturnType<typeof gamesGetGameState>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  gameId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof gamesGetGameState>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get the full state of a specific game
 */

export function useGamesGetGameState<
  TData = Awaited<ReturnType<typeof gamesGetGameState>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  gameId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof gamesGetGameState>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGamesGetGameStateQueryOptions(gameId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
