/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * (title)
 * API for a custom three-player chess variant game server. Authentication is required via a JWT Bearer token for protected endpoints.
 * OpenAPI spec version: 0.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  BadRequestError,
  ConflictError,
  CreateTournament,
  ForbiddenError,
  InternalError,
  NotFoundError,
  ReadTournament,
  UnauthorizedError,
} from ".././model";

import { customInstance } from ".././mutator/custom-instance";
import type { ErrorType } from ".././mutator/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Get list of all tournaments
 */
export const tournamentsListTournaments = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ReadTournament[]>(
    { url: `/api/tournaments/`, method: "GET", signal },
    options,
  );
};

export const getTournamentsListTournamentsQueryKey = () => {
  return [`/api/tournaments/`] as const;
};

export const getTournamentsListTournamentsQueryOptions = <
  TData = Awaited<ReturnType<typeof tournamentsListTournaments>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof tournamentsListTournaments>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getTournamentsListTournamentsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof tournamentsListTournaments>>
  > = ({ signal }) => tournamentsListTournaments(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof tournamentsListTournaments>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TournamentsListTournamentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof tournamentsListTournaments>>
>;
export type TournamentsListTournamentsQueryError = ErrorType<
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | InternalError
>;

export function useTournamentsListTournaments<
  TData = Awaited<ReturnType<typeof tournamentsListTournaments>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof tournamentsListTournaments>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof tournamentsListTournaments>>,
          TError,
          Awaited<ReturnType<typeof tournamentsListTournaments>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useTournamentsListTournaments<
  TData = Awaited<ReturnType<typeof tournamentsListTournaments>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof tournamentsListTournaments>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof tournamentsListTournaments>>,
          TError,
          Awaited<ReturnType<typeof tournamentsListTournaments>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useTournamentsListTournaments<
  TData = Awaited<ReturnType<typeof tournamentsListTournaments>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof tournamentsListTournaments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get list of all tournaments
 */

export function useTournamentsListTournaments<
  TData = Awaited<ReturnType<typeof tournamentsListTournaments>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof tournamentsListTournaments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getTournamentsListTournamentsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create a new tournament - Admin only
 */
export const tournamentsCreateTournament = (
  createTournament: CreateTournament,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ReadTournament>(
    {
      url: `/api/tournaments/create`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createTournament,
      signal,
    },
    options,
  );
};

export const getTournamentsCreateTournamentMutationOptions = <
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tournamentsCreateTournament>>,
    TError,
    { data: CreateTournament },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof tournamentsCreateTournament>>,
  TError,
  { data: CreateTournament },
  TContext
> => {
  const mutationKey = ["tournamentsCreateTournament"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tournamentsCreateTournament>>,
    { data: CreateTournament }
  > = (props) => {
    const { data } = props ?? {};

    return tournamentsCreateTournament(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TournamentsCreateTournamentMutationResult = NonNullable<
  Awaited<ReturnType<typeof tournamentsCreateTournament>>
>;
export type TournamentsCreateTournamentMutationBody = CreateTournament;
export type TournamentsCreateTournamentMutationError = ErrorType<
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | InternalError
>;

/**
 * @summary Create a new tournament - Admin only
 */
export const useTournamentsCreateTournament = <
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof tournamentsCreateTournament>>,
      TError,
      { data: CreateTournament },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof tournamentsCreateTournament>>,
  TError,
  { data: CreateTournament },
  TContext
> => {
  const mutationOptions =
    getTournamentsCreateTournamentMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
