/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * (title)
 * API for a custom three-player chess variant game server. Authentication is required via a JWT Bearer token for protected endpoints.
 * OpenAPI spec version: 0.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AssignBotPayload,
  BadRequestError,
  ConflictError,
  CreateBot,
  ForbiddenError,
  InternalError,
  NotFoundError,
  ReadBot,
  UnauthorizedError,
  UpdateBot,
} from ".././model";

import { customInstance } from ".././mutator/custom-instance";
import type { ErrorType } from ".././mutator/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Get list of all bots
 */
export const botsListBots = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ReadBot[]>(
    { url: `/api/bots/`, method: "GET", signal },
    options,
  );
};

export const getBotsListBotsQueryKey = () => {
  return [`/api/bots/`] as const;
};

export const getBotsListBotsQueryOptions = <
  TData = Awaited<ReturnType<typeof botsListBots>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof botsListBots>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBotsListBotsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof botsListBots>>> = ({
    signal,
  }) => botsListBots(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof botsListBots>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BotsListBotsQueryResult = NonNullable<
  Awaited<ReturnType<typeof botsListBots>>
>;
export type BotsListBotsQueryError = ErrorType<
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | InternalError
>;

export function useBotsListBots<
  TData = Awaited<ReturnType<typeof botsListBots>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof botsListBots>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof botsListBots>>,
          TError,
          Awaited<ReturnType<typeof botsListBots>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBotsListBots<
  TData = Awaited<ReturnType<typeof botsListBots>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof botsListBots>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof botsListBots>>,
          TError,
          Awaited<ReturnType<typeof botsListBots>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBotsListBots<
  TData = Awaited<ReturnType<typeof botsListBots>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof botsListBots>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get list of all bots
 */

export function useBotsListBots<
  TData = Awaited<ReturnType<typeof botsListBots>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof botsListBots>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getBotsListBotsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Assign a bot to a game - Admin / Owner only
 */
export const botsAssignBot = (
  assignBotPayload: AssignBotPayload,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    {
      url: `/api/bots/assign`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: assignBotPayload,
      signal,
    },
    options,
  );
};

export const getBotsAssignBotMutationOptions = <
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof botsAssignBot>>,
    TError,
    { data: AssignBotPayload },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof botsAssignBot>>,
  TError,
  { data: AssignBotPayload },
  TContext
> => {
  const mutationKey = ["botsAssignBot"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof botsAssignBot>>,
    { data: AssignBotPayload }
  > = (props) => {
    const { data } = props ?? {};

    return botsAssignBot(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type BotsAssignBotMutationResult = NonNullable<
  Awaited<ReturnType<typeof botsAssignBot>>
>;
export type BotsAssignBotMutationBody = AssignBotPayload;
export type BotsAssignBotMutationError = ErrorType<
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | InternalError
>;

/**
 * @summary Assign a bot to a game - Admin / Owner only
 */
export const useBotsAssignBot = <
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof botsAssignBot>>,
      TError,
      { data: AssignBotPayload },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof botsAssignBot>>,
  TError,
  { data: AssignBotPayload },
  TContext
> => {
  const mutationOptions = getBotsAssignBotMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Create a new bot user - Admin only
 */
export const botsCreate = (
  createBot: CreateBot,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ReadBot>(
    {
      url: `/api/bots/create`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createBot,
      signal,
    },
    options,
  );
};

export const getBotsCreateMutationOptions = <
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof botsCreate>>,
    TError,
    { data: CreateBot },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof botsCreate>>,
  TError,
  { data: CreateBot },
  TContext
> => {
  const mutationKey = ["botsCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof botsCreate>>,
    { data: CreateBot }
  > = (props) => {
    const { data } = props ?? {};

    return botsCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type BotsCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof botsCreate>>
>;
export type BotsCreateMutationBody = CreateBot;
export type BotsCreateMutationError = ErrorType<
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | InternalError
>;

/**
 * @summary Create a new bot user - Admin only
 */
export const useBotsCreate = <
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof botsCreate>>,
      TError,
      { data: CreateBot },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof botsCreate>>,
  TError,
  { data: CreateBot },
  TContext
> => {
  const mutationOptions = getBotsCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete a bot user (changes the user type back to Regular) - Admin only
 */
export const botsDelete = (
  botId: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/api/bots/delete/${botId}`, method: "DELETE" },
    options,
  );
};

export const getBotsDeleteMutationOptions = <
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof botsDelete>>,
    TError,
    { botId: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof botsDelete>>,
  TError,
  { botId: number },
  TContext
> => {
  const mutationKey = ["botsDelete"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof botsDelete>>,
    { botId: number }
  > = (props) => {
    const { botId } = props ?? {};

    return botsDelete(botId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type BotsDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof botsDelete>>
>;

export type BotsDeleteMutationError = ErrorType<
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | InternalError
>;

/**
 * @summary Delete a bot user (changes the user type back to Regular) - Admin only
 */
export const useBotsDelete = <
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof botsDelete>>,
      TError,
      { botId: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof botsDelete>>,
  TError,
  { botId: number },
  TContext
> => {
  const mutationOptions = getBotsDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get available bot model keys
 */
export const botsModelKeys = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<string[]>(
    { url: `/api/bots/keys`, method: "GET", signal },
    options,
  );
};

export const getBotsModelKeysQueryKey = () => {
  return [`/api/bots/keys`] as const;
};

export const getBotsModelKeysQueryOptions = <
  TData = Awaited<ReturnType<typeof botsModelKeys>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof botsModelKeys>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBotsModelKeysQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof botsModelKeys>>> = ({
    signal,
  }) => botsModelKeys(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof botsModelKeys>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BotsModelKeysQueryResult = NonNullable<
  Awaited<ReturnType<typeof botsModelKeys>>
>;
export type BotsModelKeysQueryError = ErrorType<
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | InternalError
>;

export function useBotsModelKeys<
  TData = Awaited<ReturnType<typeof botsModelKeys>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof botsModelKeys>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof botsModelKeys>>,
          TError,
          Awaited<ReturnType<typeof botsModelKeys>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBotsModelKeys<
  TData = Awaited<ReturnType<typeof botsModelKeys>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof botsModelKeys>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof botsModelKeys>>,
          TError,
          Awaited<ReturnType<typeof botsModelKeys>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBotsModelKeys<
  TData = Awaited<ReturnType<typeof botsModelKeys>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof botsModelKeys>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get available bot model keys
 */

export function useBotsModelKeys<
  TData = Awaited<ReturnType<typeof botsModelKeys>>,
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof botsModelKeys>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getBotsModelKeysQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update an existing bot's configuration - Admin
 */
export const botsUpdate = (
  botId: number,
  updateBot: UpdateBot,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<ReadBot>(
    {
      url: `/api/bots/update/${botId}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateBot,
    },
    options,
  );
};

export const getBotsUpdateMutationOptions = <
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof botsUpdate>>,
    TError,
    { botId: number; data: UpdateBot },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof botsUpdate>>,
  TError,
  { botId: number; data: UpdateBot },
  TContext
> => {
  const mutationKey = ["botsUpdate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof botsUpdate>>,
    { botId: number; data: UpdateBot }
  > = (props) => {
    const { botId, data } = props ?? {};

    return botsUpdate(botId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type BotsUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof botsUpdate>>
>;
export type BotsUpdateMutationBody = UpdateBot;
export type BotsUpdateMutationError = ErrorType<
  | BadRequestError
  | UnauthorizedError
  | ForbiddenError
  | NotFoundError
  | ConflictError
  | InternalError
>;

/**
 * @summary Update an existing bot's configuration - Admin
 */
export const useBotsUpdate = <
  TError = ErrorType<
    | BadRequestError
    | UnauthorizedError
    | ForbiddenError
    | NotFoundError
    | ConflictError
    | InternalError
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof botsUpdate>>,
      TError,
      { botId: number; data: UpdateBot },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof botsUpdate>>,
  TError,
  { botId: number; data: UpdateBot },
  TContext
> => {
  const mutationOptions = getBotsUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
