/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * (title)
 * API for a custom three-player chess variant game server. Authentication is required via a JWT Bearer token for protected endpoints.
 * OpenAPI spec version: 0.0.0
 */

export interface BotCreate {
  username: string;
  model_key: string;
  playouts_per_move: number;
  exploration_factor: number;
  virtual_loss: number;
  contempt: number;
  password: string;
}
