/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * (title)
 * API for a custom three-player chess variant game server. Authentication is required via a JWT Bearer token for protected endpoints.
 * OpenAPI spec version: 0.0.0
 */

export type FilterGames = (typeof FilterGames)[keyof typeof FilterGames];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FilterGames = {
  Waiting: "Waiting",
  InProgress: "InProgress",
  Finished: "Finished",
} as const;
