/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * (title)
 * API for a custom three-player chess variant game server. Authentication is required via a JWT Bearer token for protected endpoints.
 * OpenAPI spec version: 0.0.0
 */
import type { GameStatePlayers } from "./gameStatePlayers";
import type { GameStatus } from "./gameStatus";
import type { GameStateSuggestedMoveTimeSeconds } from "./gameStateSuggestedMoveTimeSeconds";
import type { GameStateTournamentId } from "./gameStateTournamentId";

export interface GameState {
  gameId: number;
  name: string;
  fen: string;
  ownerId: number;
  ownerUsername: string;
  players: GameStatePlayers;
  status: GameStatus;
  players_masked: boolean;
  material_masked: boolean;
  training_mode: boolean;
  suggested_move_time_seconds: GameStateSuggestedMoveTimeSeconds;
  tournamentId: GameStateTournamentId;
}
