/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * (title)
 * API for a custom three-player chess variant game server. Authentication is required via a JWT Bearer token for protected endpoints.
 * OpenAPI spec version: 0.0.0
 */
import type { PromotionPiece } from "./promotionPiece";

export interface MakeMovePayload {
  /**
   * @minimum 0
   * @maximum 96
   */
  fromIndex: number;
  /**
   * @minimum 0
   * @maximum 96
   */
  toIndex: number;
  promotion?: PromotionPiece;
}
