/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * (title)
 * API for a custom three-player chess variant game server. Authentication is required via a JWT Bearer token for protected endpoints.
 * OpenAPI spec version: 0.0.0
 */
import type { User } from "./user";

export interface UserCreated {
  /** The JWT token to be used for authenticating subsequent requests. */
  token: string;
  user: User;
}
