/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * (title)
 * API for a custom three-player chess variant game server. Authentication is required via a JWT Bearer token for protected endpoints.
 * OpenAPI spec version: 0.0.0
 */
import type { WsEventJoined } from "./wsEventJoined";
import type { WsEventLeft } from "./wsEventLeft";
import type { WsEventStarted } from "./wsEventStarted";
import type { WsEventEnded } from "./wsEventEnded";
import type { WsEventMoveMade } from "./wsEventMoveMade";
import type { WsEventOnJoin } from "./wsEventOnJoin";
import type { WsEventPlayerUpdate } from "./wsEventPlayerUpdate";

export type WsEvent =
  | WsEventJoined
  | WsEventLeft
  | WsEventStarted
  | WsEventEnded
  | WsEventMoveMade
  | WsEventOnJoin
  | WsEventPlayerUpdate;
