/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * (title)
 * API for a custom three-player chess variant game server. Authentication is required via a JWT Bearer token for protected endpoints.
 * OpenAPI spec version: 0.0.0
 */
import type { WsEventMoveMadeKind } from "./wsEventMoveMadeKind";
import type { WsMoveMade } from "./wsMoveMade";

export interface WsEventMoveMade {
  kind: WsEventMoveMadeKind;
  value: WsMoveMade;
}
