/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * (title)
 * API for a custom three-player chess variant game server. Authentication is required via a JWT Bearer token for protected endpoints.
 * OpenAPI spec version: 0.0.0
 */

export type WsEventJoinedKind =
  (typeof WsEventJoinedKind)[keyof typeof WsEventJoinedKind];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WsEventJoinedKind = {
  joined: "joined",
} as const;
